### ISSUE TITLE
Multiple changes to SPASE School Website

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/spase-school#10]
Hello Chuck,
I've attached 4 screen shots. 
SPASE School change 1: 
--Change SPASE Metadata Working Group to SPASE Metadata Working Team
--Remove all content from SPASE SQL an
![SPASE School change 1](https://github.com/spase-group/spase-school/assets/108490588/b0e3345d-d565-4631-867b-53964bfe813c)
d below

SPASE School Change 2:
--1st highlight: Change the SPASE mailing (listserv address) to SPASE@groups.io
--2nd highlight: change to spase-support@groups.io
--3rd highlight: change to SPASE@groups.io
![Spase School change 2](https://github.com/spase-group/spase-school/assets/108490588/c0f52e93-4aff-44b9-9b76-38ea392dc163)

SPASE School Change 3:
--First Highlight change to "Team (SMWT)"
--2nd highlight change to "team"
--3rd highlight change to https://hdrl.gsfc.nasa.gov/smwt_home/smwt_index.html
--4th highlight change to spase-support@groups.io
![Spase school change 3](https://github.com/spase-group/spase-school/assets/108490588/8e142e1c-39e4-422e-ba85-81d6c4569da8)

SPASE School Change 5:
--When I click the validation button, nothing happens
![SPASE School change 5](https://github.com/spase-group/spase-school/assets/108490588/69093d9e-e5e9-434c-86ac-e212284f9aba)

**Comment by cfdolan** [comment]
Same issue as the Dictionary anchor tag: https://github.com/spase-group/spase-school/issues/9#issuecomment-1631146593

**Comment by tressahelvey** [comment]
Resolved
