### ISSUE TITLE
Broken Links on SPASE Website

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/spase-school#8]
Please fix the broken links below:
SPASE Tutorials: Broken Links
•	SPASE group Registry: https://hpde.io/registry/explorer
•	SMWG Registry: https://hpde.io/registry/search
•	Resources Descriptor Editor: https://spase-group.org/tools/xmleditor/base/ 
•	SPASE online validation tool: https://spase-group.org/tools/validate 

http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Instrument
http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Observatory
http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Person
http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Registry

http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Catalog

http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Annotation

**Comment by cfdolan** [comment]
Completed 2023/06/14

**Comment by cfdolan** [comment]
If you're clicking on the links above as they're spelled out in the ticket, yeah they won't resolve because they're the incorrect links. You want to be looking at the links at the spase-school site itself:
https://school.spase-group.org/intro.html 

example:
http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Instrument 
is now
https://spase-group.org/data/model/spase-2.5.0/spase-2_5_0_xsd.html#Instrument
etc.

**Comment by tressahelvey** [comment]
Well, that makes sense. Sorry for the false alarm.
Thanks. Tressa


______________________________
Regards,
Tressa Helvey-Kasulke
NASA/Goddard Space Flight Center
Project Manager, HDRL
Cell: 202-870-4363

From: cfdolan ***@***.***>
Sent: Tuesday, June 20, 2023 12:40 PM
To: spase-group/spase-school ***@***.***>
Cc: Helvey-Kasulke, Tressa L. (GSFC-672.0)[ASRC FEDERAL SYSTEM SOLUTIONS] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [spase-group/spase-school] Broken Links on SPASE Website (Issue #8)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



If you're clicking on the links above as they're spelled out in the ticket, yeah they won't resolve because they're the incorrect links. You want to be looking at the links at the spase-school site itself:
https://school.spase-group.org/intro.html

example:
http://spase-group.org/data/model/spase-2_3_1/spase-2_3_1_xsd.htm#http___www.spase-group.org_data_schema_Spase_Instrument
is now
https://spase-group.org/data/model/spase-2.5.0/spase-2_5_0_xsd.html#Instrument
etc.

-

**Comment by tressahelvey** [comment]
Issue closed
