### ISSUE TITLE
SPASE Dictionary not showing

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/spase-school#9]
When the following link is clicked, you get no results.

https://school.spase-group.org/docs/dictionary.html#Dictionary

Please link to the dictionary.

**Comment by cfdolan** [comment]
This link works now.

**Comment by tressahelvey** [comment]
Hello Chuck, as of today, when I click the link, the dictionary does not open. I've tried two different browsers. Can you get it to open? 
![SPASE School change 4](https://github.com/spase-group/spase-school/assets/108490588/a0081dc9-68dc-42ce-81c6-8dbebbe66ef3)

**Comment by cfdolan** [comment]
It's an anchor link to the same page:
https://school.spase-group.org/docs/dictionary.html 
https://school.spase-group.org/docs/dictionary.html#Dictionary 

but the page is so shallow there is no browser motion. At this point the Dictionary link should probably be removed or hidden.
